version:'3.7'

services:
  disorder:
    container_name:disorder
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/nodemodules'
    ports:
      - '3000:3000'
    environment: 
      - NODEENV=development
      - CHOKIDAR_USEPOLLING=true